name: Test and build the sample app

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:

  build-sdk:
    runs-on: macos-latest
    steps:
      # init
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # build and test
      - name: Build SDK
        run: ./gradlew erdkotlin:build
      - name: Test SDK
        run: ./gradlew erdkotlin:test

  build-app:
    needs: build-sdk
    runs-on: macos-latest
    steps:
      # init
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # build and test
      - name: Build App
        run: ./gradlew app:build
      - name: Test App
        run: ./gradlew app:test

