name: Test and build the sample app

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-erdkotlin:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: |
          ./gradlew build
